version: '3.8'
services:
  dev-db:
    image: postgres:13
    volumes:
      - db_data:/var/lib/postgresql/data  
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: demo123
      POSTGRES_DB: gamificationDB
    networks:
      - my_app

networks:
  my_app:

volumes:
  db_data:
